### ISSUE TITLE
Color legend for plate maps

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/LabControl#432]
Plate map cells change color after an entry has been added. Sometimes, it's not clear to the wetlab what the colors represent.

**Comment by charles-cowart** [comment]
Either Amanda or myself would be the best people to handle this; it doesn't need to be both people.

**Comment by charles-cowart** [comment]
@fedarko This would be a nice to have for the full launch, but it's just not as high a priority as the other issues. This would be a good thing for George to dig through the code and document, and if he needs help you might be able to provide it, since you're also working in the plate-mapper area.

**Comment by fedarko** [comment]
@charles-cowart Got it! Between George and I, I think this issue should be handleable.

FYI to @gwarmstrong: from what I can tell, the code that handles the individual well styles does this via CSS classes (which seem to all be defined [here](https://github.com/jdereus/LabControl/blob/master/labcontrol/gui/static/css/labcontrol.css#L27)). I would imagine that we could solve this fairly simply by just applying each of these classes to a `<div>` or something, and then wrapping all of that off to the side of the big plate div. (Charlie, feel free to yell at me if this is summary is lacking :)

**Comment by charles-cowart** [comment]
@fedarko there will be no yelling. :)

**Comment by gwarmstrong** [comment]
I currently have a mock up going for this [here](https://github.com/gwarmstrong/LabControl/tree/issue432-cell-colors)

Before:
![Screen Shot 2019-08-15 at 10 34 18 AM](https://user-images.githubusercontent.com/19470970/63114476-c6c7a000-bf49-11e9-8de7-a97e34d3754f.png)

After:
![Screen Shot 2019-08-15 at 10 35 26 AM](https://user-images.githubusercontent.com/19470970/63114482-cb8c5400-bf49-11e9-864a-6bd99cd2faa0.png)

@charles-cowart  @fedarko Thoughts on the initial layout? I can move this over to a PR if more appropriate

**Comment by charles-cowart** [comment]
@gwarmstrong Looks great, thanks! I think moving two of them to the right to make it a 2x2 square rather than a 1x4 is a better use of space; it'll prevent people from having to scroll down more to view the entire legend.

**Comment by gwarmstrong** [comment]
@charles-cowart 
How about now?
![Screen Shot 2019-08-15 at 11 25 38 AM](https://user-images.githubusercontent.com/19470970/63116874-81a66c80-bf4f-11e9-8e18-226914abb38f.png)

**Comment by gwarmstrong** [comment]
Also, is there any way to get feedback from the lab on whether the legend descriptions are reasonable?

**Comment by charles-cowart** [comment]
Amanda and I looked them over and we have a few comments I'll pass on later
this afternoon.

**Comment by gwarmstrong** [comment]
Great, should I go ahead and submit a PR, and we can handle the commenting there?

**Comment by charles-cowart** [comment]
sure! I'll add them as part of a review
