### ISSUE TITLE
User can pass >4 gdna plates to compression page from plate list, leading to ugly error

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/LabControl#488]
Reproduction gif below.  From plate list, user can pick more than 4 gDNA plates for compression, which is illegal but is not checked on compression.html page when plates come in via querystring rather than being added on that page natively.

![compression_checkbox_issues](https://user-images.githubusercontent.com/10677935/56758735-353ee300-674c-11e9-89f5-278cc904d038.gif)

Also see #485 : these are both errors related to the checkbox functionality in the plate list sending unacceptable inputs to the downstream pages, which accept them in a way that escapes their usual front-end validity checks and allows the bad input to make it through to the server, leading to big ugly errors.

 I see this as a relatively low priority because the folks in the lab are not stupid and are unlikely to *try* to compress 5 plates together since they know their process only supports 4.

**Comment by charles-cowart** [comment]
This looks like a gentle introduction to the LabControl codebase for @fedarko and @qiyunzhu . Bumping it to the full-release, as it looks relatively simple to do, and adds to the robustness of the system. I suggest also adding text that appears saying that only up to four plates can be checked at a time.

**Comment by AmandaBirmingham** [comment]
@charles-cowart : Not against having @fedarko and @qiyunzhu take this on. However, all, please be aware that although this sounds straightforward, the functionality for passing plates from the plate list to various pages (because different kinds of plates are able to go to different kinds of pages, and in different numbers, and yadda yadda) is really surprisingly bug-prone.  I personally would rather see the entire ability to pass plates from the list page to the action pages torn out as an unnecessary complication, although I suppose I won't be able to convince anyone of that ...
