### ISSUE TITLE
Correct misspelling of Kapa (not kappa) Hyper Plus name throughout application

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/LabControl#506]
Per @wasade:

From: Daniel McDonald
Date: Wednesday, May 8, 2019 at 2:56 PM

<snip />

One thing that Greg noted: It’s Kapa not kappa… :/
 
https://sequencing.roche.com/en/products-solutions/by-category/library-preparation/dna-library-preparation/kapa-hyperplus.html

@charles-cowart  is already using the correct spelling in the shotgun prep sheet generation, so that doesn't need to be touched.   Simple search and replace throughout the code-base (be sure to check sql and docs as well ... I see it is mentioned in index.rst ...) should do it.

Not a high priority because no one is confused about what the current misspelled labels actually mean :)

**Comment by charles-cowart** [comment]
https://github.com/jdereus/labman/pull/502#discussion_r282708951

Plan is to revert instances of {K|k}apa to kappa in order to be more consistent, and change only the column name in the final prep file output to 'Kapa'.

**Comment by charles-cowart** [comment]
Resolved with:
https://github.com/jdereus/LabControl/pull/547
https://github.com/jdereus/LabControl/pull/548
