### ISSUE TITLE
Relocate definition of assay types

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/LabControl#513]
This issue is related to but not entirely the same as #480 Assay types are not fully centralized , and it should be addressed before adding any new protocols to the software.

There are several places in the code that decide what to do based on checking the assay type.  Right now this assay type is a property of the SequencingProcess (see `assay` on the `sequencing_process` table, below) :

![Screen Shot 2019-05-09 at 1 59 56 PM](https://user-images.githubusercontent.com/10677935/57490345-c98d6780-726d-11e9-98a0-68b8aed17be7.png)

However, as time goes on I am not entirely sure that is where it should be: the value for that field is actually set based on the types of **pool component compositions** of the pools being fed into the SequencingProcess, which supports the idea that this is actually a property of a PoolComposition rather than of a SequencingProcess:

https://github.com/jdereus/labman/blob/46241e448edd4fc615aeea914e8dd80bf88aad79/labcontrol/db/process.py#L2709-L2725

Furthermore, it turns out we need to check what kind of "assay" a Pool is at various points before we actually have the SequencingProcess (e.g., everywhere we use the PoolListHandler.get, which is called by the /pool_list url that is accessed by `pool_list.html`, `pool_pooling.html`, and `sequencing.html`.

Finally, right now the assay types are identified by a particular *string* that is *hard-coded* in the SequencingProcess:

https://github.com/jdereus/labman/blob/46241e448edd4fc615aeea914e8dd80bf88aad79/labcontrol/db/process.py#L2630-L2631

It seems likely that the "assay" property (a) should be moved off the SequencingProcess and onto the PoolComposition and (b) should have its potential values defined in a database table.

This issue also relates to #509 Centralize and harden identification of pool component types.

**Comment by charles-cowart** [comment]
Tentatively assigned to full launch, as it may impact implementing MiniPCR. A little concerned that this property and/or the classes themselves are not well-defined, if what this property is a property of is that subjective. Will investigate.

**Comment by AmandaBirmingham** [comment]
@charles-cowart I strongly feel we should do this for MiniPCR.  Agree that it is a bit murky what this is a property of, but I think now is the time to hash that out.

**Comment by charles-cowart** [comment]
Thanks for your input! I’ll reassign it to full launch this evening.
