### ISSUE TITLE
Extend SequencingProcess._format_sample_sheet to handle more than two assay types

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/LabControl#514]
This issue is related to #513 Assay types are not fully centralized and #513 Relocate definition of assay types. 

There are *numerous* places within `SequencingProcess._format_sample_sheet` that currently assume there are only two potential types of assays: either amplicon or metagenomics (shotgun), and thus decide which action to take just by looking at the boolean `self.is_amplicon_assay`:

https://github.com/jdereus/labman/blob/46241e448edd4fc615aeea914e8dd80bf88aad79/labcontrol/db/process.py#L3113-L3157

This must be changed before adding any new protocols to the software or they will incorrectly be treated as metagenomics assays regardless of what they really are.

**Comment by charles-cowart** [comment]
Needed for support of MiniPCR. Assigned to full launch

**Comment by AmandaBirmingham** [comment]
+1 for needed for support of MiniPCR
