### ISSUE TITLE
Add another cell color, for the case where there are multiple "matches" for a tube ID in multiple studies being plated

### ISSUE THREAD

**Issue by fedarko** [jdereus/LabControl#565]
@charles-cowart and I whiteboarded this out. This issue will need to be taken care of after #553 is addressed (and "matching" of the pasted-in IDs with study IDs is done automatically in the JavaScript side of things upon pasting multiple cells from excel/google sheets/etc).

Essentially: if multiple studies (let's say with study ID `2` and study ID `99`) are being plated simultaneously, it's possible for the same tube ID to have multiple possible matches.

1. Let's assume that study 2 contains a sample with the ID `2.ABC`.
2. Let's assume that study 99 contains a sample with the ID `99.2.ABC`.
3. Say the user enters in the ID `2.ABC` in a well.

The hypothetical "matching" code in JS would identify both `2.ABC` and `99.2.ABC` as possible matches for this input (since it will check two things: first for exact matches against available samples in the plated studies, then for exact-matches-with-the-plated-study-IDs-prepended). The user will have to manually disambiguate this case by selecting the correct sample ID to use.

Although this is an "error" case—that is, just keeping the initially entered ID in the well is invalid—none of the current well "decorators" really cover this (as documented in the [in-progress legend](https://github.com/jdereus/LabControl/pull/564)). Charlie and I agreed that we will need another color that corresponds to "this cell has multiple possible matches and needs manual examination," or something like that. (We agreed on using yellow as the color, but if anyone wants a different style I'm sure we can pick another color. :)

**Comment by charles-cowart** [comment]
Resolved in PR #566
